params:
  2bRAD_M:
    path: "/home/jiezhu/toolkit/2bRAD-M"
  mash:
    threads: 8
    batch_num: 30 
    kmer_size: 21                 # [1-32]
    sketch_size: 1000
    seed: 2022                  # [0-4294967296]
    probability_threshold: 0.01 # [0-1]
    max_pvalue: 1.0             # [0-1]
    max_distance: 1.0           # [0-1]

input:
  genomes: "gtdb207_genome_paths.tsv.h"

output:
  2bRAD_M: "/lustre1/u/jiezhu/projects/2bRAD-M/assay/gtdb_tag_test/results"
